### PR TITLE
Fix typo in README (wrong library name)

### PR DESCRIPTION
**Pull request by chrischtel**
I corrected the modulename from 'httpz' to 'zcsv' in the README file on Line 93

### CODE REVIEW

**Comment by matthewtolman** [comment]
Thank you!

**Comment by chrischtel** [comment]
> Thank you!

This was my first contribution to any project here on Github. Hope it helped. I am trying to learn zig so I am open for easy issues on this project.

**Comment by matthewtolman** [comment]
Thank you for the interest @chrischtel!

Right now I'm mostly bug hunting and working on improving performance. Most of my work is currently in the 0.4.x-dev branch. In that branch I recently reworked the memory layout of rows from allocating parsers to improve performance (which also required some API changes). Other than that, I'm mostly just finding different CSV files on kaggle and running them through each parser to see there are any bugs (e.g. parse errors, incorrectly parsed data, incorrect number of fields, etc.). 

The parsers I'm testing are `raw` (all of my non-simd algorithms stem from this parser), `stream.FieldStreamPartial` (what the allocating parsers use), `map_ck`/`map_sk`, `column`, `slice.fields` (`slice.row` just loops over this parser), and `stream_fast`. The `slice.*` and `stream_fast` are the most complicated and bug-prone parsers, so that's where a lot of my focus has been.

Currently I don't have any outstanding bugs, but once I do I'll post an issue and you can pick it up if you want. If you're interested in bug hunting and reporting issues, then that'd be helpful as well.

Additional help would be with feedback from the usability side of things. I wrote all of these parsers for my personal needs, and since I know them really well it doesn't bother me if there is something more difficult or non-intuitive with usage patterns. Feedback on how to make them more friendly to other developers would be appreciated. The main parsers I'm concerned with are `map_sk`, `map_ck` and `column`.

There is a refactor task that I can add an issue for if you're interested. As part of my rework on the 0.4.x-dev branch I dropped the need for the `stream.FieldStream` parser. I would like to drop the `stream.FieldStream` parser entirely, rename `stream.FieldStreamPartial` to `stream.Parser`, and add an `init` method to initialize a new `stream.Parser` (similar to the init methods I have in my other files).

At some point, once the `stream_fast` parser has been heavily tested, I'd like to move the `column` parser to use `stream_fast` instead. However, right now I'm not very confident that `stream_fast` is bug-free, so I'm holding off on that conversion.

Let me know what you're interested in and I'll get some issues added that you can pick up.

**Comment by matthewtolman** [comment]
I posted an issue for the refactor work. Feel free to assign yourself if you'd like. Issue: https://github.com/matthewtolman/zig_csv/issues/2

**Comment by chrischtel** [comment]
Hey, I can't assign myself but I will have a look at the issue!

**Comment by chrischtel** [comment]
First of all, thanks for giving me the opportunities to contribute to your project.
In general I am open for refactoring things and small / easy tasks. You can always create an issue and I can look through them to see what I can do (or not).

**Pull request merged**
